@Library('jenkins-shared-lib@master')_

pipeline {
    agent any

    environment {
        githubCredentialsId = "github-access-waclaw-mikolajczyk"
        gitUrl = "https://github.com/wac-mik/sandbox.git"
        gitUsername = "Waclaw Mikolajczyk"
        gitUserEmail = "user@mail.com"
        gitHubPath = "wac-mik/sandbox.git"
    }

    options {
        timestamps()
    }

    parameters {
        string(name: 'branch', defaultValue: 'main', description: 'branch to checkout')
        string(name: 'fileName' ,description: 'Filename to commit' )
        string(name: 'contentFile', description: 'Content of the filename')
        string(name: 'commitMessage', description: 'Commit message')
    }

    stages {
        stage("Stage 1") {
            steps {
                script {
                    scmUtils.gitCheckout(
                        branch: params.branch,
                        url: env.gitUrl,
                        credentialsId: env.githubCredentialsId
                    )
                }
                writeFile file: params.fileName, text: params.contentFile
                script {
                    scmUtils.setGitUserName(env.gitUsername)
                    scmUtils.setGitUserEmail(env.gitUserEmail)
                    scmUtils.commit (message: params.commitMessage)
                    scmUtils.push(
                        credentialsId: env.githubCredentialsId,
                        gitHubPath: env.gitHubPath)
                    }

                }
            }
        }
}
