@Library('jenkins-shared-lib@master')_

pipeline {
    agent any
    environment {
        githubCredentialsId = "github-access-waclaw-mikolajczyk"
        gitUsername = "Waclaw Mikolajczyk"
        gitUserEmail = "user@mail.com"
        gitHubPath = "wac-mik/sandbox.git"
    }
    parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'master', description: '')
        string(name: 'FILE_NAME', description: '' )
        string(name: 'FILE_CONTENT', description: '')
        string(name: 'GIT_COMMIT_MESSAGE', description: '')
    }
    options {
        timestamps()
    }
    stages {
        stage("Stage 1") {
            steps {
                script {
                    scmUtils.gitCheckout(
                        branch: params.GIT_BRANCH,
                        url: "https://github.com/${env.gitHubPath}",
                        credentialsId: env.githubCredentialsId
                    )
                }
                writeFile (
                    file: params.FILE_NAME,
                    text: params.FILE_CONTENT
                )
                script {
                    scmUtils.setGitUserName(env.gitUsername)
                    scmUtils.setGitUserEmail(env.gitUserEmail)
                    scmUtils.commit (message: params.GIT_COMMIT_MESSAGE)
                    scmUtils.push(
                        credentialsId: env.githubCredentialsId,
                        gitHubPath: env.gitHubPath
                    )
                }
            }
        }
    }
}
